AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaName:
    Description: Name of the lambda function
    Type: String
  LambdaPolicyPrefix:
    Description: PascalCase prefix for any policies attached to the lambda's IAM role
    Type: String
  LambdaRoleName:
    Description: Name of the lambda function's role
    Type: String
  LambdaDescription:
    Description: Description of the lambda function's purpose
    Type: String
  LambdaMemorySize:
    Description: Total memory size of the lambda's runtime
    Type: Number
  LambdaTimeout:
    Description: The maximum amount of time (in seconds) the Lambda allows a function to run before stopping it
    Type: Number

Resources:
  LambdaCloudWatchPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref LambdaFunctionRole
      PolicyName: !Sub "${LambdaPolicyPrefix}LambdaCloudWatchPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaName}:*"

  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${LambdaRoleName}"
      Description: Role for the Golang Lambda Function
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${LambdaName}"
      Handler: bootstrap
      MemorySize: !Ref LambdaMemorySize
      PackageType: Zip
      Architectures:
        - arm64
      Runtime: provided.al2023
      Role: !Ref LambdaFunctionRole
      Description: !Sub "${LambdaDescription}"
      Code:
        S3Bucket: lambda-bucket
        S3Key: !Sub "${LambdaName}.zip"
      Timeout: !Ref LambdaTimeout
      LoggingConfig:
        LogFormat: JSON
        LogGroup: !Sub "/aws/lambda/${LambdaName}"
